package interceptor

import (
	"go/ast"
	"go/parser"
	"go/token"
	"reflect"
	"testing"

	"golang.org/x/tools/go/analysis"
)

func TestSkipGeneratedFile(t *testing.T) {
	for _, test := range []struct {
		name      string
		source    string
		wantCount int
	}{
		{
			name:      "generated",
			source:    "// Code generated by test. DO NOT EDIT.\n\npackage p\n",
			wantCount: 0,
		},
		{name: "ordinary", source: "package p\n", wantCount: 1},
	} {
		t.Run(test.name, func(t *testing.T) {
			_, count := runTestAnalyzer(t, test.source, SkipGeneratedFile)
			if count != test.wantCount {
				t.Fatalf("diagnostic count = %d, want %d", count, test.wantCount)
			}
		})
	}
}

func TestSkipByDirective(t *testing.T) {
	tests := []struct {
		name      string
		source    string
		wantCount int
	}{
		{name: "file", source: "//importalias:ignore demo\n\npackage p\n", wantCount: 0},
		{name: "same line", source: "package p\nvar value = 1 //importalias:ignore demo\n", wantCount: 0},
		{name: "previous line", source: "package p\n//importalias:ignore demo\nvar value = 1\n", wantCount: 0},
		{name: "wrong tool", source: "package p\nvar value = 1 //other:ignore demo\n", wantCount: 1},
		{name: "wrong analyzer", source: "package p\nvar value = 1 //importalias:ignore other\n", wantCount: 1},
		{name: "space after slash", source: "package p\nvar value = 1 // importalias:ignore demo\n", wantCount: 1},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			_, count := runTestAnalyzer(t, test.source, SkipByDirective("importalias"))
			if count != test.wantCount {
				t.Fatalf("diagnostic count = %d, want %d", count, test.wantCount)
			}
		})
	}
}

func TestWithAppliesInterceptorsInOrder(t *testing.T) {
	var got []string
	base := &analysis.Analyzer{
		Name: "demo",
		Run: func(pass *analysis.Pass) (any, error) {
			got = append(got, "run")
			return nil, nil
		},
	}
	wrap := func(name string) Func {
		return func(a *analysis.Analyzer) *analysis.Analyzer {
			original := a.Run
			a.Run = func(pass *analysis.Pass) (any, error) {
				got = append(got, name+" before")
				result, err := original(pass)
				got = append(got, name+" after")
				return result, err
			}
			return a
		}
	}

	wrapped := With(base, wrap("first"), wrap("second"))
	_, _ = wrapped.Run(&analysis.Pass{})
	want := []string{"second before", "first before", "run", "first after", "second after"}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("interceptor order = %v, want %v", got, want)
	}
}

func runTestAnalyzer(t *testing.T, source string, fs ...Func) (*ast.File, int) {
	t.Helper()
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, "test.go", source, parser.ParseComments)
	if err != nil {
		t.Fatal(err)
	}
	count := 0
	position := file.Package
	if len(file.Decls) > 0 {
		position = file.Decls[len(file.Decls)-1].Pos()
	}
	analyzer := With(&analysis.Analyzer{
		Name: "demo",
		Run: func(pass *analysis.Pass) (any, error) {
			pass.Report(analysis.Diagnostic{Pos: position, End: position})
			return nil, nil
		},
	}, fs...)
	_, err = analyzer.Run(&analysis.Pass{
		Fset:   fset,
		Files:  []*ast.File{file},
		Report: func(analysis.Diagnostic) { count++ },
	})
	if err != nil {
		t.Fatal(err)
	}
	return file, count
}
